#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 20 14:48:53 CDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto d3b6e360b91b42a49326a08b658fa2ec --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot p7BTH_behav xil_defaultlib.p7BTH -log elaborate.log"
xelab -wto d3b6e360b91b42a49326a08b658fa2ec --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot p7BTH_behav xil_defaultlib.p7BTH -log elaborate.log

