#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 22 17:14:48 CDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim p4TB_behav -key {Behavioral:sim_1:Functional:p4TB} -tclbatch p4TB.tcl -view /home/brandon/Documentos/PRACTICA 4/practica4/p4TB_behav.wcfg -log simulate.log"
xsim p4TB_behav -key {Behavioral:sim_1:Functional:p4TB} -tclbatch p4TB.tcl -view /home/brandon/Documentos/PRACTICA 4/practica4/p4TB_behav.wcfg -log simulate.log

