#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Oct 29 21:04:44 CDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 2934c1245a454653a0851688f4a6057d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot memProg_tb_behav xil_defaultlib.memProg_tb -log elaborate.log"
xelab -wto 2934c1245a454653a0851688f4a6057d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot memProg_tb_behav xil_defaultlib.memProg_tb -log elaborate.log

