#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 22 11:13:57 CST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto b159c79762a641a890cdf8b68ffbfede --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot P9bth_behav xil_defaultlib.P9bth -log elaborate.log"
xelab -wto b159c79762a641a890cdf8b68ffbfede --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot P9bth_behav xil_defaultlib.P9bth -log elaborate.log

