#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Oct 05 18:34:50 CDT 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 833b332d52cf4c2e827a95786db29291 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot alu1bth_behav xil_defaultlib.alu1bth -log elaborate.log"
xelab -wto 833b332d52cf4c2e827a95786db29291 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot alu1bth_behav xil_defaultlib.alu1bth -log elaborate.log

